### PR TITLE
Add DIT046, DIT033, DIT182 exams

### PR DESCRIPTION
**Pull request by michalspano**
This **PR** adds exams from the following courses:
- `DIT046`
- `DIT033`
- `DIT182` (submodule)

### CODE REVIEW

**Comment by harring** [comment]
It seems some numbers got lost when changing names of files. 

- exams/DIT046/2022-01-12/DIT046 Student answers 20112.pdf
- exams/DIT046/2022-04-13/DIT046 Exam 20413.pdf
- exams/DIT046/2022-04-13/DIT046 Student answers 20413 1.pdf
- exams/DIT046/2022-04-13/DIT046 Student answers 20413 2.pdf

**Comment by michalspano** [comment]
> It seems some numbers got lost when changing names of files.
> 
>     * exams/DIT046/2022-01-12/DIT046 Student answers 20112.pdf
> 
>     * exams/DIT046/2022-04-13/DIT046 Exam 20413.pdf
> 
>     * exams/DIT046/2022-04-13/DIT046 Student answers 20413 1.pdf
> 
>     * exams/DIT046/2022-04-13/DIT046 Student answers 20413 2.pdf

Let me see!

**Comment by michalspano** [comment]
Should be fixed noQ

**Comment by harring** [comment]
I added the links to the new folders in the readme, forgot to mention it in my comment.
Now it looks good to me.

**Review by harring — APPROVED** [review]

**Comment by michalspano** [comment]
I see, cool, thanks for that! I'm **merging** to `main` with no conflicts.

**Pull request merged**
